apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octopus
  template:
    metadata:
      labels:
        app: octopus
    spec:
      containers:
        - image: registry.cloud.okteto.net/tomaszczerminski/domain:latest
          name: domain
        - image: registry.cloud.okteto.net/tomaszczerminski/api:latest
          name: api

---

apiVersion: v1
kind: Service
metadata:
  name: octopus
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "octopus"
      port: 8080
  selector:
    app: octopus
