apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: registry.cloud.okteto.net/tomaszczerminski/api:latest
          name: api

---

apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "api"
      port: 8080
  selector:
    app: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain
  template:
    metadata:
      labels:
        app: domain
    spec:
      containers:
        - image: registry.cloud.okteto.net/tomaszczerminski/domain:latest
          name: domain

---

apiVersion: v1
kind: Service
metadata:
  name: domain
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "domain"
      port: 8080
  selector:
    app: domain