on:
  push:
    branches:
      - master

name: Build and Deploy

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        env:
          token: ${{ secrets.OKTETO_TOKEN }}
        uses: okteto/login@master

      - name: "Activate Namespace"
        uses: okteto/namespace@master
        with:
          name: tomaszczerminski

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@master
        with:
          name: okteto-pipeline.yml
          timeout: 8m