on:
  push:
    branches:
      - master

name: Build and Deploy

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@master
        with:
          name: tomaszczerminski

      - name: "Destroy the pipeline"
        uses: okteto/destroy-pipeline@master
        continue-on-error: true
        with:
          name: octopus

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@master
        with:
          name: octopus
          timeout: 8m